# Generated by Django 5.2.13 on 2026-05-28 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0002_produto_genero_alter_categoria_id_alter_produto_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='tamanhos',
            field=models.CharField(blank=True, help_text='Digite os tamanhos separados por vírgula. Ex: P, M, G, GG ou 38, 40, 42', max_length=100, null=True),
        ),
    ]
