# Generated by Django 6.0.5 on 2026-05-24 19:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagamentos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='atualizado_em',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='id_pagamento_mp',
        ),
        migrations.AddField(
            model_name='pedido',
            name='recompensa_processada',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='status',
            field=models.CharField(default='pendente', max_length=20),
        ),
    ]
