# Generated by Django 6.0.5 on 2026-05-24 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagamentos', '0003_itempedido'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='id_pagamento_mp',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
